export const labels = {
  common: {
    loading: "読み込み中...",
    loadFailed: "読み込みに失敗しました",
    cancel: "キャンセル",
    save: "保存",
    saving: "保存中...",
    delete: "削除",
    edit: "編集",
    create: "作成",
    update: "更新",
    register: "登録",
    registering: "登録中...",
    search: "検索",
    all: "すべて",
    viewAll: "すべて見る",
    prev: "前へ",
    next: "次へ",
    select: "選択してください",
    required: "必須",
    optional: "任意",
    online: "オンライン",
    offline: "来院",
    doctor: "担当",
    date: "日付",
    time: "時間",
    status: "ステータス",
    action: "操作",
    taxIncluded: "(税込)",
    default: "デフォルト",
    draft: "下書き",
    new: "新着",
    retry: "再読み込み",
  },

  pages: {
    dashboard: {
      title: "ダッシュボード",
      greeting: (name: string) => `${name}さん、おはようございます`,
      stats: {
        patients: "患者数",
        todayAppointments: "本日の予約",
        pendingPrescriptions: "未処理処方",
        monthlyRevenue: "今月の売上",
      },
      sections: {
        todayAppointments: "本日の予約",
        recentPatients: "最近の患者",
      },
      empty: {
        appointments: "本日の予約はありません",
        patients: "患者データがありません",
      },
    },

    patients: {
      title: "患者管理",
      description: "患者情報の登録・管理",
      newPatient: "新規患者登録",
      searchPlaceholder: "患者名、患者番号、電話番号で検索...",
      listTitle: (count: number) => `患者一覧 (${count}件)`,
      table: {
        patientNumber: "患者番号",
        name: "氏名",
        gender: "性別",
        birthDate: "生年月日",
        phone: "電話番号",
        insuranceNumber: "保険番号",
      },
      gender: {
        MALE: "男性",
        FEMALE: "女性",
        OTHER: "その他",
      },
      empty: "患者データがありません",
    },

    patientDetail: {
      title: "患者詳細",
      sections: {
        profile: "基本情報",
        contact: "連絡先",
        insurance: "保険情報",
        medical: "医療情報",
        recentRecords: "最近の診療記録",
        recentAppointments: "最近の予約",
        recentPrescriptions: "最近の処方",
      },
      empty: {
        records: "診療記録がありません",
        appointments: "予約がありません",
        prescriptions: "処方がありません",
      },
    },

    staffDetail: {
      title: "スタッフ詳細",
      sections: {
        profile: "プロフィール",
        stats: "実績",
      },
      labels: {
        email: "メールアドレス",
        specialization: "専門",
        licenseNumber: "医師免許番号",
        joinedAt: "登録日",
      },
      stats: {
        appointments: "予約",
        records: "診療記録",
        prescriptions: "処方",
      },
    },

    appointments: {
      title: "予約管理",
      description: "診療予約の管理・スケジュール確認",
      newAppointment: "新規予約",
      calendar: "カレンダー",
      dateTitle: (date: string) => `${date} の予約`,
      empty: "この日の予約はありません",
      viewMode: {
        list: "一覧",
        day: "日",
        week: "週",
        month: "月",
      },
      navigation: {
        today: "今日",
        thisWeek: "今週",
        thisMonth: "今月",
      },
      doctorLabel: "担当:",
      actions: {
        checkIn: "受付",
        start: "開始",
        startOnline: "オンライン診療開始",
        preparing: "準備中...",
        complete: "完了",
        cancel: "予約をキャンセル",
        revertToScheduled: "予約済みに戻す",
        revertToWaiting: "受付済みに戻す",
        revertToInProgress: "診療中に戻す",
        revertCancellation: "キャンセルを取り消す",
      },
      detail: {
        statusTimeline: {
          scheduled: "予約済み",
          waiting: "受付完了",
          inProgress: "診療中",
          completed: "完了",
          cancelled: "キャンセル済み",
          noShow: "来院なし",
        },
        sections: {
          dateTime: "予約日時",
          doctor: "担当医",
          consultationType: "診療形態",
          reason: "予約理由",
        },
        consultationType: {
          online: "オンライン診療",
          inPerson: "来院診療",
        },
        badge: {
          online: "オンライン",
        },
      },
      schedule: {
        appointmentCount: (count: number) => `${count}件の予約`,
        moreAppointments: (count: number) => `+${count}件`,
      },
    },

    records: {
      title: "診療記録",
      description: "カルテの閲覧・作成 (SOAP形式)",
      newRecord: "新規カルテ作成",
      patientSelect: "患者選択:",
      patientPlaceholder: "患者を選択してください",
      empty: "診療記録がありません",
      createFirst: "最初のカルテを作成",
      soap: {
        chiefComplaint: "主訴",
        subjective: "S (Subjective)",
        objective: "O (Objective)",
        assessment: "A (Assessment)",
        plan: "P (Plan)",
        prescription: "処方",
      },
    },

    video: {
      title: "オンライン診療",
      description: "ビデオ通話による診療",
      todayOnline: "本日のオンライン診療",
      empty: "本日のオンライン診療予約はありません",
      startConsultation: "診療開始",
      instructions: {
        title: "オンライン診療について",
        preparation: {
          title: "1. 事前準備",
          description: "カメラとマイクが正常に動作することを確認してください",
        },
        start: {
          title: "2. 診療開始",
          description: "「診療開始」ボタンをクリックしてビデオ通話を開始します",
        },
        end: {
          title: "3. 診療終了",
          description: "診療が終わったら「終了」ボタンで通話を終了してください",
        },
      },
    },

    prescriptions: {
      title: "処方管理",
      description: "処方箋の管理・調剤状況の確認",
      statusFilter: "ステータス:",
      listTitle: (count: number) => `処方一覧 (${count}件)`,
      table: {
        date: "処方日",
        patient: "患者",
        medication: "薬剤名",
        dosage: "用法・用量",
        days: "日数",
        doctor: "担当医",
      },
      filter: {
        all: "すべて",
        pending: "未処理",
        dispensed: "調剤済",
        cancelled: "キャンセル",
      },
      actions: {
        dispensed: "調剤済",
      },
      empty: "処方データがありません",
    },

    billing: {
      title: "請求管理",
      description: "請求書の作成・管理",
      newInvoice: "新規請求書",
      stats: {
        monthlyRevenue: "今月の売上",
        unpaidCount: "未払い件数",
        overdueCount: "期限超過",
      },
      statusFilter: "ステータス:",
      listTitle: (count: number) => `請求書一覧 (${count}件)`,
      table: {
        invoiceNumber: "請求番号",
        date: "請求日",
        patient: "患者",
        amount: "金額",
        dueDate: "支払期限",
      },
      filter: {
        all: "すべて",
        draft: "下書き",
        sent: "送付済",
        paid: "支払済",
        overdue: "期限超過",
        cancelled: "キャンセル",
      },
      actions: {
        send: "送付",
        confirmPayment: "支払確認",
      },
      empty: "請求書がありません",
    },

    questionnaire: {
      title: "Web問診",
      description: "問診テンプレートの管理と回答の確認",
      templateManagement: "テンプレート管理",
      stats: {
        unconfirmed: "未確認の問診",
        todayResponses: "今日の回答",
        templateCount: "テンプレート数",
        totalResponses: "総回答数",
      },
      tabs: {
        responses: "問診回答",
        templates: "テンプレート",
      },
      sections: {
        unconfirmed: "未確認の問診回答",
        responseList: "問診回答一覧",
      },
      confirmHint: "確認してカルテに反映してください",
      newTemplate: "新規テンプレート",
      templatesEmpty: "テンプレートがありません",
      templatesCreateFirst: "最初のテンプレートを作成",
      categories: {
        all: "すべて",
        general: "一般",
        initial: "初診",
        followup: "再診",
        pediatrics: "小児科",
        internal: "内科",
        ent: "耳鼻科",
        dermatology: "皮膚科",
        orthopedics: "整形外科",
        psychiatry: "心療内科",
        other: "その他",
      },
      status: {
        draft: "下書き",
        submitted: "提出済み",
        confirmed: "確認済み",
        applied: "カルテ適用済み",
      },
      empty: "問診回答がありません",
    },

    documents: {
      title: "文書管理",
      description: "紹介状・診断書・各種証明書のテンプレートと作成",
      stats: {
        templateCount: "テンプレート数",
        issuedDocuments: "発行済み文書",
        referralLetters: "紹介状",
        certificates: "診断書",
      },
      tabs: {
        templates: "テンプレート",
        issued: "発行済み文書",
      },
      newTemplate: "新規テンプレート",
      createFirst: "最初のテンプレートを作成",
      categories: {
        all: "すべて",
        referral: "紹介状",
        certificate: "診断書",
        medicalCertificate: "医療証明書",
        prescription: "処方箋",
        consent: "同意書",
        leaveOfAbsence: "休職証明書",
        insurance: "保険関係書類",
        other: "その他",
      },
      empty: {
        templates: "テンプレートがありません",
        issued: "発行済み文書がありません",
      },
      dialog: {
        editTitle: "テンプレートの編集",
        newTitle: "新規テンプレート",
        placeholderHint: "プレースホルダーを使用できます: {{患者名}}, {{患者番号}}, {{生年月日}}, {{発行日}}, {{年齢}}",
        form: {
          name: "テンプレート名",
          category: "カテゴリ",
          description: "説明",
          content: "テンプレート内容",
        },
      },
    },

    settings: {
      title: "設定",
      description: "アカウント設定とシステム設定",
      sections: {
        profile: { title: "プロフィール", description: "アカウント情報" },
        organization: { title: "組織情報", description: "所属クリニック情報" },
        security: { title: "セキュリティ", description: "セキュリティ設定" },
        notifications: { title: "通知設定", description: "通知の受信設定" },
        system: { title: "システム情報" },
      },
      labels: {
        name: "氏名",
        email: "メールアドレス",
        role: "役割",
        tenantId: "テナントID",
        password: "パスワード",
        twoFactor: "二段階認証",
        appointmentReminder: "予約リマインダー",
        emailNotification: "メール通知",
      },
      actions: {
        change: "変更",
      },
      status: {
        enabled: "有効",
        disabled: "無効",
      },
      hints: {
        lastUpdated: "最終更新: 未設定",
        twoFactorHint: "追加のセキュリティ層",
        orgChangeHint: "組織情報の変更は管理者にお問い合わせください。",
        reminderHint: "予約前に通知",
        emailHint: "重要な更新をメールで受信",
      },
      system: {
        version: "バージョン",
        environment: "環境",
        videoApi: "ビデオAPI",
        database: "データベース",
        values: {
          version: "1.0.0",
          environment: "Production",
          videoApi: "Daily.co",
          database: "PostgreSQL",
        },
      },
      roles: {
        ADMIN: "管理者",
        DOCTOR: "医師",
        NURSE: "看護師",
        STAFF: "スタッフ",
        PATIENT: "患者",
      },
    },

    ent: {
      title: "耳鼻科検査",
      description: "聴力検査・内視鏡・平衡機能検査など",
      dashboard: "ダッシュボード",
      diagnosisTemplates: "診断テンプレート",
      newExam: (type: string) => `新規${type}`,
      patientSelect: "患者選択:",
      patientPlaceholder: "患者を選択してください",
      tabs: {
        audiometry: "聴力検査",
        tympanometry: "ティンパノ",
        vestibular: "平衡機能",
        endoscopy: "内視鏡",
        allergy: "アレルギー",
      },
      fullNames: {
        audiometry: "聴力検査",
        tympanometry: "ティンパノメトリー",
        vestibular: "平衡機能検査",
        endoscopy: "内視鏡検査",
        allergy: "アレルギー検査",
      },
    },

    entDashboard: {
      title: "耳鼻科ダッシュボード",
      description: "検査統計と最近の活動",
      viewTests: "検査一覧へ",
      stats: {
        totalTests: "総検査数",
        last30Days: "直近30日",
      },
      sections: {
        hearingDistribution: "聴力レベル分布",
        hearingDescription: "全聴力検査結果の分布（左右耳別）",
        recentTests: "最近の検査",
        recentDescription: "直近の検査記録",
        quickActions: "クイックアクション",
      },
      empty: {
        hearing: "聴力検査データがありません",
        tests: "検査データがありません",
      },
      actions: {
        recordTest: "検査を記録",
        templates: "テンプレート管理",
        patients: "患者一覧",
        records: "診療記録",
      },
    },

    entTemplates: {
      title: "診断テンプレート管理",
      description: "よく使う診断・所見・処方をテンプレート化",
      breadcrumbParent: "耳鼻科検査",
      breadcrumbCurrent: "診断テンプレート",
      filterLabel: "カテゴリで絞り込み:",
      newTemplate: "新規テンプレート",
      empty: "テンプレートがありません",
      createFirst: "最初のテンプレートを作成",
      deleteTitle: "テンプレートを削除しますか？",
      deleteDescription: "この操作は取り消せません。テンプレートは完全に削除されます。",
      deleteAction: "削除",
      categories: {
        ALL: "すべて",
        EAR: "耳疾患",
        NOSE: "鼻疾患",
        THROAT: "咽喉頭疾患",
        ALLERGY: "アレルギー",
        VERTIGO: "めまい",
        OTHER: "その他",
      },
    },

    analytics: {
      title: "経営分析ダッシュボード",
      description: "クリニックの経営状況を可視化",
      stats: {
        monthlyRevenue: "今月の売上",
        monthlyConsultations: "今月の診療件数",
        monthlyAppointments: "今月の予約件数",
        monthlyNewPatients: "今月の新患数",
      },
      comparison: "前月比",
      charts: {
        dailyConsultations: "日別診療件数 (過去30日)",
        monthlyRevenue: "月別売上推移 (過去12ヶ月)",
      },
      sections: {
        patientRatio: "新患・再診比率",
        hourlyDistribution: "時間帯別予約分布",
        doctorStats: "医師別診療件数",
        unpaidStatus: "未収金状況",
        todayAppointments: "本日の予約",
      },
      period: {
        last30Days: "過去30日間",
      },
      patientTypes: {
        initial: "初診",
        followup: "再診",
      },
      unpaid: {
        unpaid: "未払い",
        overdue: "延滞",
      },
      empty: {
        data: "データがありません",
        appointments: "本日の予約はありません",
      },
    },

    login: {
      systemName: "電子カルテ・オンライン診療システム",
      demoAccount: "デモアカウント:",
      demoCredentials: {
        admin: "admin@example.com / password",
        doctor: "doctor@example.com / password",
      },
    },
  },

  portal: {
    home: {
      title: "マイページ",
      description: "診療情報やお知らせを確認できます",
      stats: {
        appointments: "予約",
        unreadMessages: "未読メッセージ",
        currentMedications: "服用中の薬",
        notifications: "お知らせ",
      },
      sections: {
        appointments: { title: "予約", description: "今後の予約" },
        messages: { title: "メッセージ", description: "クリニックからのメッセージ" },
        medications: { title: "お薬手帳", description: "服用中のお薬" },
        notifications: { title: "お知らせ", description: "クリニックからのお知らせ" },
      },
      bookAppointment: "予約を取る",
      empty: {
        appointments: "予約はありません",
        messages: "メッセージはありません",
        medications: "服用中の薬はありません",
        notifications: "お知らせはありません",
      },
      appointmentType: {
        online: "オンライン診療",
        inPerson: "来院",
      },
      status: {
        confirmed: "確定",
        scheduled: "予約済",
      },
    },

    appointments: {
      title: "予約",
      description: "診療予約の確認",
      stats: {
        upcoming: "今後の予約",
        confirmed: "確定済み",
        online: "オンライン",
        past: "過去の予約",
      },
      tabs: {
        upcoming: "今後の予約",
        past: "過去の予約",
      },
      empty: {
        upcoming: "今後の予約はありません",
        past: "過去の予約はありません",
      },
      status: {
        scheduled: "予約済",
        confirmed: "確定",
        cancelled: "キャンセル",
        completed: "完了",
        noShow: "未来院",
      },
      doctorLabel: (name: string) => `担当: ${name || "未定"}`,
      startConsultation: "診療を開始",
      location: {
        online: "オンライン診療",
        inPerson: "来院",
      },
    },

    medications: {
      title: "お薬手帳",
      description: "服用中のお薬を管理できます",
      addMedication: "お薬を追加",
      stats: {
        active: "服用中",
        total: "合計",
        prescription: "処方薬",
      },
      tabs: {
        active: "服用中",
        all: "すべて",
      },
      empty: {
        active: "服用中の薬はありません",
        all: "お薬の記録はありません",
      },
      dialog: {
        editTitle: "お薬を編集",
        addTitle: "お薬を追加",
        description: "服用中のお薬を記録します",
      },
      form: {
        name: "お薬の名前",
        type: "種類",
        dosage: "用量",
        instructions: "服用方法",
        startDate: "開始日",
        endDate: "終了日",
        notes: "備考",
      },
      types: {
        PRESCRIPTION: "処方薬",
        OTC: "市販薬",
        SUPPLEMENT: "サプリメント",
      },
      properties: {
        instructions: "服用方法",
        startDate: "開始日",
        endDate: "終了日",
      },
    },

    messages: {
      title: "メッセージ",
      description: "クリニックとのやり取り",
      newMessage: "新規メッセージ",
      inbox: "受信トレイ",
      empty: {
        list: "メッセージはありません",
        select: "メッセージを選択してください",
      },
      noSubject: "（件名なし）",
      sender: {
        clinic: "クリニック",
        you: "あなた",
      },
      dialog: {
        title: "新規メッセージ",
        description: "クリニックへのお問い合わせを送信できます",
      },
      form: {
        subject: "件名",
        body: "本文",
        subjectPlaceholder: "件名を入力",
        bodyPlaceholder: "メッセージを入力...",
      },
      actions: {
        send: "送信",
        sending: "送信中...",
      },
    },

    results: {
      title: "検査結果",
      description: "過去の検査結果を確認できます",
      stats: {
        total: "検査件数",
        normal: "正常",
        abnormal: "要確認",
      },
      empty: "検査結果はありません",
      badge: {
        abnormal: "要確認",
        normal: "正常",
      },
      properties: {
        resultLabel: "検査結果",
        referenceRange: "基準値:",
        notes: "備考:",
      },
    },

    notifications: {
      title: "お知らせ",
      description: "クリニックからのお知らせ",
      markAllAsRead: "すべて既読にする",
      stats: {
        total: "すべてのお知らせ",
        unread: "未読",
      },
      listTitle: "お知らせ一覧",
      empty: "お知らせはありません",
      markAsRead: "既読にする",
    },
  },

  dialogs: {
    patient: {
      editTitle: "患者情報編集",
      newTitle: "新規患者登録",
      sections: {
        basic: "基本情報",
        contact: "連絡先",
        insurance: "保険情報",
        medical: "医療情報",
      },
      form: {
        patientNumber: "患者番号",
        gender: "性別",
        lastName: "姓",
        firstName: "名",
        lastNameKana: "姓（カナ）",
        firstNameKana: "名（カナ）",
        birthDate: "生年月日",
        bloodType: "血液型",
        phone: "電話番号",
        email: "メールアドレス",
        postalCode: "郵便番号",
        address: "住所",
        emergencyContactName: "緊急連絡先（氏名）",
        emergencyContactPhone: "緊急連絡先（電話）",
        insuranceNumber: "保険証番号",
        insuranceType: "保険種別",
        allergies: "アレルギー",
        medicalHistory: "既往歴",
        notes: "備考",
      },
      placeholders: {
        patientNumber: "P0001",
        lastName: "山田",
        firstName: "太郎",
        lastNameKana: "ヤマダ",
        firstNameKana: "タロウ",
        phone: "090-1234-5678",
        email: "example@email.com",
        postalCode: "123-4567",
        address: "東京都渋谷区...",
        emergencyContactName: "山田花子（妻）",
        emergencyContactPhone: "090-9876-5432",
        insuranceType: "国民健康保険",
        allergies: "薬剤アレルギー、食物アレルギーなど",
        medicalHistory: "過去の病歴、手術歴など",
        notes: "その他の注意事項",
      },
      bloodTypes: ["A+", "A-", "B+", "B-", "O+", "O-", "AB+", "AB-"],
    },

    appointment: {
      title: "新規予約",
      form: {
        patient: "患者",
        doctor: "担当医",
        date: "日付",
        startTime: "開始時間",
        endTime: "終了時間",
        type: "診療種別",
        isOnline: "オンライン診療",
        reason: "予約理由",
      },
      placeholders: {
        patient: "患者を選択",
        doctor: "担当医を選択",
        reason: "来院理由や症状など",
      },
      onlineHint: "ビデオ通話で診療を行います",
      types: {
        INITIAL: "初診",
        FOLLOWUP: "再診",
        CONSULTATION: "相談",
        CHECKUP: "健診",
        EMERGENCY: "緊急",
      },
      validation: {
        patient: "患者を選択してください",
        doctor: "担当医を選択してください",
        date: "日付を選択してください",
        startTime: "開始時間を入力してください",
        endTime: "終了時間を入力してください",
      },
    },

    record: {
      editTitle: "診療記録編集",
      newTitle: "新規診療記録",
      tabs: {
        soap: "SOAP記録",
        ent: "耳鼻科",
        vitals: "バイタル",
        basic: "基本情報",
      },
    },
  },

  messages: {
    success: {
      patientCreated: "患者を登録しました",
      patientUpdated: "患者情報を更新しました",
      appointmentCreated: "予約を登録しました",
      recordSaved: "診療記録を保存しました",
      recordUpdated: "診療記録を更新しました",
      dispensed: "調剤済みに更新しました",
      cancelled: "キャンセルしました",
      statusUpdated: "ステータスを更新しました",
      paymentRecorded: "支払いを記録しました",
      templateCreated: "テンプレートを作成しました",
      templateUpdated: "テンプレートを更新しました",
      templateDeleted: "テンプレートを削除しました",
      medicationAdded: "お薬を追加しました",
      medicationUpdated: "お薬を更新しました",
      medicationDeleted: "お薬を削除しました",
      messageSent: "メッセージを送信しました",
      consultationEnded: "診療を終了しました",
    },
    error: {
      loginFailed: "メールアドレスまたはパスワードが正しくありません",
      loginError: "ログインに失敗しました",
      patientCreateFailed: "登録に失敗しました",
      patientUpdateFailed: "更新に失敗しました",
      appointmentCreateFailed: "登録に失敗しました",
      appointmentUpdateFailed: "更新に失敗しました",
      invoiceUpdateFailed: "更新に失敗しました",
      paymentRecordFailed: "支払い記録に失敗しました",
      templateDeleteFailed: "削除に失敗しました",
      recordSaveFailed: "保存に失敗しました",
      recordUpdateFailed: "更新に失敗しました",
      onlineConsultationFailed: "オンライン診療の開始に失敗しました",
      consultationEndFailed: "診療の終了に失敗しました",
      requiredFields: "必須項目を入力してください",
      subjectAndBodyRequired: "件名と本文を入力してください",
    },
  },
} as const;

export type Labels = typeof labels;
